### ISSUE TITLE
The link to the documentation is raising a 404 error

### ISSUE THREAD

**Issue by mariohsouto** [JuliaLang/Precompiler.jl#4]
The link to the docs, "https://julialang.github.io/Precompiler.jl/stable/", is returning a 404 error.

**Comment by timholy** [comment]
For now change the URL from `/stable` to `/dev`. This package isn't released yet (and further changes are likely, perhaps even including a renaming, see #2), but when it does get released the `/stable` link will start working. I don't see a good reason to change it now because I might forget to revert it to `/stable` after it gets released, which is a much bigger problem.

**Comment by mariohsouto** [comment]
Thanks for the help.
